### ISSUE TITLE
mistake in readme.md package name 

### ISSUE THREAD

**Issue by anasfik** [relaystr/dart_ndk#13]
Hi,

I was researching the name for the Dart client package for Nostr that I am maintaining on GitHub search, [dart_nostr](https://github.com/anasfik/nostr), so it finds it on your `readme.md` file at [Get ](https://github.com/relaystr/dart_ndk#getting-started) Starting to add in `pubspec.yaml`

This will make users install my package instead of yours, causing them being confused. it should be `dart_ndk`

Cheers,
Anas

**Comment by frnandu** [comment]
oh shit, thanks for letting me know, fixed.
