### ISSUE TITLE
native signature verification in C or Rust

### ISSUE THREAD

**Issue by frnandu** [relaystr/dart_ndk#4]

**Comment by leo-lox** [comment]
tested out in:
https://github.com/relaystr/dart_ndk/tree/rust_ffi
https://github.com/relaystr/dart_ndk/tree/rust_bridge_test

decision: Works well => start implementation

implmentation starts once
https://github.com/relaystr/dart_ndk/blob/master/docs/ADRs/layerd-architecture.md
complete

**Comment by leo-lox** [comment]
https://github.com/relaystr/dart_ndk/commit/fc4bcb4dca82f548edac851096d2df513d923c77
